blog:
  search:
    kakao:
      apiUri: https://dapi.kakao.com/v2/search/blog
      apiKey: 88e92474ef68c4e8d97a02aa07777352

    naver:
      apiUri: https://openapi.naver.com/v1/search/blog.json
      clientId: ddEMQzJuBE9jZft8LU63
      clientSecret: TTSomaV6A_

server:
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:h2:./circuit
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create