### 단축URL 생성
POST http://localhost:8080/shorten
Content-Type: application/json

{
  "title": "남자맨투맨",
  "id": 112,
  "originalUrl": "http://localhost:8080/product/112"
}

### 단축URL 요청
GET http://localhost:8080/%EB%82%A8%EC%9E%90%EB%A7%A8%ED%88%AC%EB%A7%A8/aVAdYN2
